import { Injectable, inject } from '@angular/core';
import { IrsApiClient } from '../../generated/generated/irs-api.client';

/**
 * Base service for all API-consuming services.
 *
 * ⚠️ ARCHITECTURE REQUIREMENT:
 * This base class enforces the mandatory use of the autogenerated IrsApiClient.
 * Services MUST extend this class and MUST NOT import HttpClient directly.
 *
 * NEVER add HttpClient as a dependency in any service.
 * ALWAYS use this.apiClient provided by this base class.
 *
 * Reference: src/ARCHITECTURE_RULES.md
 *
 * @example
 * ```typescript
 * export class AuthService extends BaseApiService {
 *   login(email: string, password: string): Observable<AuthResponse> {
 *     const request = new LoginRequest({ email, password });
 *     return this.apiClient.auth_Login(request).pipe(
 *       map(response => response.result)
 *     );
 *   }
 * }
 * ```
 */
@Injectable()
export abstract class BaseApiService {
  /**
   * Autogenerated API client from NSwag.
   * This is the ONLY way to make API calls in any service.
   *
   * ⚠️ DO NOT bypass this by importing HttpClient directly.
   * ⚠️ DO NOT hardcode API paths.
   * ⚠️ DO NOT create custom HTTP calls.
   *
   * All API calls MUST go through this client.
   */
  protected readonly apiClient = inject(IrsApiClient);
}
