// This file will be auto-generated by NSwag
// Placeholder content - will be replaced when NSwag runs
import { InjectionToken, Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

export const API_BASE_URL_TOKEN = new InjectionToken<string>('API_BASE_URL');

// Placeholder types - will be replaced when NSwag runs
export interface UserDto {
  id: number;
  userName: string;
}

export interface CreateUserDto {
  userName: string;
}

export interface PiResponseDto {
  message: string;
  pi: number;
  piFormatted: string;
}

// Placeholder clients - will be replaced when NSwag runs
@Injectable({
  providedIn: 'root'
})
export class UsersClient {
  private http = inject(HttpClient);
  private baseUrl = inject(API_BASE_URL_TOKEN, { optional: true }) || '';

  getUsers(): Observable<UserDto[]> {
    return this.http.get<UserDto[]>(`${this.baseUrl}/api/users`);
  }

  createUser(dto: CreateUserDto): Observable<UserDto> {
    return this.http.post<UserDto>(`${this.baseUrl}/api/users`, dto);
  }

  deleteUser(id: number): Observable<void> {
    return this.http.delete<void>(`${this.baseUrl}/api/users/${id}`);
  }
}

@Injectable({
  providedIn: 'root'
})
export class PiClient {
  private http = inject(HttpClient);
  private baseUrl = inject(API_BASE_URL_TOKEN, { optional: true }) || '';

  getHelloPi(): Observable<PiResponseDto> {
    return this.http.get<PiResponseDto>(`${this.baseUrl}/api/pi/hello`);
  }
}
