/**
 * ⚠️ ARCHITECTURE REQUIREMENT:
 * This service MUST use IrsApiClient from the autogenerated client.
 * NEVER import HttpClient directly.
 * See: src/ARCHITECTURE_RULES.md
 */

import { Injectable, inject } from '@angular/core';
import { Observable, tap, map } from 'rxjs';
import { BaseApiService } from '../../core/base-api.service';
import { AuthResponse, LoginRequest, RegisterRequest } from '../../../generated/generated/irs-api.client';


export interface AuthToken {
  token: string;
  expiresIn: number;
  expiresAt: number;
}

@Injectable({
  providedIn: 'root'
})
export class AuthService extends BaseApiService {
  private readonly TOKEN_KEY = 'auth_token';
  private readonly USER_KEY = 'auth_user';

  /**
   * Register a new user with email, password, and full name
   */
  register(email: string, password: string, fullName: string): Observable<AuthResponse> {
    const request = new RegisterRequest({
      email,
      password,
      fullName
    });

    return this.apiClient.auth_Register(request).pipe(
      map((response) => response.result),
      tap((response) => {
        if (response) {
          this.storeAuthData(response);
        }
      })
    );
  }

  /**
   * Login with email and password
   */
  login(email: string, password: string): Observable<AuthResponse> {
    const request = new LoginRequest({
      email,
      password
    });

    return this.apiClient.auth_Login(request).pipe(
      map((response) => response.result),
      tap((response) => {
        if (response) {
          this.storeAuthData(response);
        }
      })
    );
  }

  /**
   * Logout the current user
   */
  logout(): void {
    localStorage.removeItem(this.TOKEN_KEY);
    localStorage.removeItem(this.USER_KEY);
  }

  /**
   * Get the stored auth token
   */
  getToken(): string | null {
    const token = localStorage.getItem(this.TOKEN_KEY);
    if (token) {
      try {
        const authToken: AuthToken = JSON.parse(token);
        // Check if token is expired
        if (authToken.expiresAt > Date.now()) {
          return authToken.token;
        } else {
          this.logout();
          return null;
        }
      } catch (error) {
        // Token is invalid or corrupted, clear storage
        console.warn('Failed to parse stored auth token', error);
        this.logout();
        return null;
      }
    }
    return null;
  }

  /**
   * Check if user is authenticated
   */
  isAuthenticated(): boolean {
    return this.getToken() !== null;
  }

  /**
   * Get stored user data
   */
  getUser(): AuthResponse | null {
    const user = localStorage.getItem(this.USER_KEY);
    if (user) {
      try {
        return JSON.parse(user);
      } catch (error) {
        console.warn('Failed to parse stored user data', error);
        this.logout();
        return null;
      }
    }
    return null;
  }

  /**
   * Store auth data in local storage
   */
  private storeAuthData(response: AuthResponse): void {
    if (response.token && response.expiresIn) {
      const authToken: AuthToken = {
        token: response.token,
        expiresIn: response.expiresIn,
        expiresAt: Date.now() + response.expiresIn * 1000
      };
      localStorage.setItem(this.TOKEN_KEY, JSON.stringify(authToken));
    }

    localStorage.setItem(this.USER_KEY, JSON.stringify(response));
  }
}
